version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: licenta-mongo-db
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_MASTER_DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_MASTER_DATABASE_PASSWORD}
    ports:
      - "27319:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  api:
    build: .  # 🔧 cheia pentru a rezolva eroarea de build
    image: licenta
    container_name: licenta-api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8111:8000"
    volumes:
      - ./src:/opt/src/src
    depends_on:
      - mongodb

volumes:
  mongo-data:
